// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb4jbBUtdmgInMx1bUeConlS_FBPMM75I',
    appId: '1:572733517438:web:78bf90eb7a8d888399b22f',
    messagingSenderId: '572733517438',
    projectId: 'meu-projeto-job-timer',
    authDomain: 'meu-projeto-job-timer.firebaseapp.com',
    storageBucket: 'meu-projeto-job-timer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHGM0C68cYLYo5-HoVR2Tf6WdgYhEE2tY',
    appId: '1:572733517438:android:65e26bea7fcc385899b22f',
    messagingSenderId: '572733517438',
    projectId: 'meu-projeto-job-timer',
    storageBucket: 'meu-projeto-job-timer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9CvuvHjPjJ_q9RBOGj5K8A8Qgce3LWLU',
    appId: '1:572733517438:ios:ef89eb98c34475a099b22f',
    messagingSenderId: '572733517438',
    projectId: 'meu-projeto-job-timer',
    storageBucket: 'meu-projeto-job-timer.appspot.com',
    iosClientId: '572733517438-0s6vm9dt09c81vi8vf8mrr5svohvvg39.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9CvuvHjPjJ_q9RBOGj5K8A8Qgce3LWLU',
    appId: '1:572733517438:ios:ef89eb98c34475a099b22f',
    messagingSenderId: '572733517438',
    projectId: 'meu-projeto-job-timer',
    storageBucket: 'meu-projeto-job-timer.appspot.com',
    iosClientId: '572733517438-0s6vm9dt09c81vi8vf8mrr5svohvvg39.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );
}
